name: 'Setup Rust Environment'
description: 'Install Rust toolchain with rustfmt and clippy, and install protobuf'
runs:
  using: 'composite'
  steps:
    - name: Setup environment with mise
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5
      with:
        cache: true

    - name: Install Rust components
      run: rustup component add rustfmt clippy
      shell: bash

    - name: Install protobuf
      run: brew install protobuf
      shell: bash

    - name: Install SwiftProtobuf
      run: brew install protobuf swift-protobuf
      shell: bash

    - name: Install XcodeGen
      run: brew install xcodegen
      shell: bash