/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Minimal proto file for agent-mobile list-targets functionality.
 */

syntax = "proto3";

package idb;

// CompanionService definition
service CompanionService {
  rpc describe(TargetDescriptionRequest) returns (TargetDescriptionResponse) {}
  rpc launch(stream LaunchRequest) returns (stream LaunchResponse) {}
  rpc screenshot(ScreenshotRequest) returns (ScreenshotResponse) {}
}

message CompanionInfo {
  string udid = 1;
  bool is_local = 4;
  bytes metadata = 6;
}

message ScreenDimensions {
  uint64 width = 1;
  uint64 height = 2;
  double density = 3;
  uint64 width_points = 4;
  uint64 height_points = 5;
}

message TargetDescription {
  string udid = 1;
  string name = 2;
  ScreenDimensions screen_dimensions = 3;
  string state = 4;
  string target_type = 5;
  string os_version = 6;
  string architecture = 7;
  bytes extended = 9;
  bytes diagnostics = 10;
}

message TargetDescriptionRequest {
  bool fetch_diagnostics = 1;
}

message TargetDescriptionResponse {
  TargetDescription target_description = 1;
  CompanionInfo companion = 2;
}

message ProcessOutput {
  enum Interface {
    STDOUT = 0;
    STDERR = 1;
  }
  Interface interface = 1;
  bytes data = 2;
}

message DebuggerInfo {
  uint64 pid = 1;
}

message LaunchRequest {
  message Start {
    string bundle_id = 1;
    map<string, string> env = 2;
    repeated string app_args = 3;
    bool foreground_if_running = 4;
    bool wait_for = 5;
    bool wait_for_debugger = 6;
  }
  message Stop {}
  oneof control {
    Start start = 1;
    Stop stop = 2;
  }
}

message LaunchResponse {
  ProcessOutput output = 3;
  DebuggerInfo debugger = 4;
}

message ScreenshotRequest {}

message ScreenshotResponse {
  bytes image_data = 1;
  string image_format = 2;
}
